### ISSUE TITLE
SSHFS Chocolatey Package

### ISSUE THREAD

**Issue by marecabo** [4O4/chocolatey-packages#1]
Hey, thanks for initially setting up a chocolatey package in https://github.com/billziss-gh/sshfs-win/issues/29. 🚀 

Is it possible to revive the [package](https://community.chocolatey.org/packages/sshfs) somehow?

**Comment by 4O4** [comment]
Hi, after 2 years of regular fights with both choco CLI and chocolatey web package upload form I was finally able to publish newer version the package. It wasn't easy because of useless error messages from their side. Once moderators review the package it should be publicly available again. I will let you know here.

```
Attempting to push sshfs.3.5.20357.nupkg to https://push.chocolatey.org/
sshfs 3.5.20357 was pushed successfully to https://push.chocolatey.org/


Your package may be subject to moderation. A moderator will review the
package prior to acceptance. You should have received an email. If you
don't hear back from moderators within 1-3 business days, please reply
to the email and ask for status or use contact site admins on the
package page to contact moderators.
```

**Comment by marecabo** [comment]
Hey @4O4, it looks like the package got approved recently. Thanks a lot for all your efforts! 🚀
